### ISSUE TITLE
how to increased FPS ?

### ISSUE THREAD

**Issue by ghost** [keijiro/NNCam#12]
Hey,
Great work its working good, 
i try this in unity version 2020.3.11 its working good but facing issues with FPS. Got maximum 2fps it very slow how to increase at least 40+ or 30+

**Comment by keijiro** [comment]
What device are you trying? Windows PC with GeForce? Or MacBook 2020 model? Or iPhone 5s?

**Comment by ghost** [comment]
MacBook Pro mid 2015, 16 GB 1600 MHz DDR3
Unity version 2020.3.11,
is it compatible with android and ios device (front camera)?

**Comment by keijiro** [comment]
> MacBook Pro mid 2015, 16 GB 1600 MHz DDR3

It should run about 30fps. I think #1 is relevant. Please try the workaround noted in the last post in #1.

> is it compatible with android and ios device (front camera)?

Yes, but it may run slower.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by ghost** [comment]
can you share any reference apk for android or example project?

**Comment by keijiro** [comment]
This repository is compatible with Android.

**Comment by ghost** [comment]
I try but camera feed not working shown only static background. camera permission allowed but not showing any camera feed with rear or front camera, i am trying to build selfie segmentation.

**Comment by keijiro** [comment]
I think your device is not compatible with GPU inference. It might be resolved by switching to CPU inference, it requires modifications to the inference code, though.

**Comment by ghost** [comment]
I am using samsung galaxy s20 fe, 1+ 7t and realme xt android device. same result too much lag and no camera feed only static background.

**Comment by keijiro** [comment]
FYI: It worked on my Pixel 5.

**Comment by ghost** [comment]
can you please sent me working apk link?

**Comment by keijiro** [comment]
IIRC, I didn't modify anything. My apk might be identical to your apk.
