### ISSUE TITLE
possible no android¿

### ISSUE THREAD

**Issue by Electricavisuals** [keijiro/NNCam#13]
Hi Mr Keijiro...
I've tried to build it in Android device, and , it compiles but, 
 I can¡'t see the small led indicating my mobile camera is on, 
and I'm getting those warnings in the console
https://imgur.com/cRVjTBL 
So, have you any suggestion?

Thnks

**Comment by keijiro** [comment]
Please check #6

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
