### ISSUE TITLE
WebCam Output is NOT showing

### ISSUE THREAD

**Issue by hyunjoebrother** [keijiro/NNCam#16]
Hello. Im university student who study Unity. 
I found your great NNCam and want to use it, but have some problem.
When I run(play) this project, I check the WebCam is Truely running cuz my laptop-camera light turn on.
However, NNcam output doesn't showing the WebCam.
I have been put release-onnx file
![errorororo](https://user-images.githubusercontent.com/66728383/184790605-76445532-3de5-49ee-a5d9-7fb060e559f2.png)
s on Assets/ONNX folder, and check another NNCam project, ex. Effect Unity project.
When I run Effect Unity project, WebCam success.
How Can I run NNCam (remove background) as right way?
Thnks. 
My Unity version is 2020.3.37f1, Barracuda version is 1.3.2
Thank You.

**Comment by keijiro** [comment]
> and check another NNCam project, ex. Effect Unity project.

Did it run successfully?

**Comment by hyunjoebrother** [comment]
>
![ffs](https://user-images.githubusercontent.com/66728383/184810808-50242c4a-ca59-464b-8e89-0506241a3c81.PNG)
 > and check another NNCam project, ex. Effect Unity project.
> 
> Did it run successfully?

Yes. No Error 😅

**Comment by keijiro** [comment]
Does your project run when you set a background texture?

**Comment by hyunjoebrother** [comment]
> 

Maybe Yes.
When I change background of Camera and Compositor(Script), its change well

**Comment by keijiro** [comment]
Then it should run without the background texture.

How it breaks when you unset the background texture? What is the symptom?

By the way, you can ignore the warning messages (messages with the yellow "!" icon).

**Comment by hyunjoebrother** [comment]
> Then it should run without the background texture.
> 
> How it breaks when you unset the background texture? What is the symptom?
> 
> By the way, you can ignore the warning messages (messages with the yellow "!" icon).

Actually, Warning or Error Message is zero. Just Camera is not Working only at this project. It doesn't break when i do not setting background either.

**Comment by keijiro** [comment]
> Just Camera is not Working only at this project.

I think the Camera worked in the first screenshot because it drew the gray background (null texture works as a gray texture).

**Comment by hyunjoebrother** [comment]
> > Just Camera is not Working only at this project.
> 
> I think the Camera worked in the first screenshot because it drew the gray background (null texture works as a gray texture).

Oh How can I put Background Texture? Its mean 'Target Texture' on Camera Component?

**Comment by keijiro** [comment]
Set the Background property of the Compositor script.

**Comment by hyunjoebrother** [comment]
> Set the Background property of the Compositor script.

Yes I did it. But jest background layer is showing. No Human😂 However Cam state is turnin on

**Comment by keijiro** [comment]
It comes back to the first question. Do the sample scenes (Room, Effect, etc.) work correctly? Does it show a person correctly?

**Comment by hyunjoebrother** [comment]
> It comes back to the first question. Do the sample scenes (Room, Effect, etc.) work correctly? Does it show a person correctly?

Yes. Effect scenes work correctly, with show a person.
When I build & run Room scene, just Room background texture is showing, not a person.

**Comment by keijiro** [comment]
So, the Compositor works in the sample scenes, but it doesn't work in scenes you newly created.

Did you set the Resources and Shader properties correctly?

**Comment by hyunjoebrother** [comment]
Yes I did. This is Room scene. No Human
![sfsd](https://user-images.githubusercontent.com/66728383/185105102-f8dd8ad8-d8f5-4d5d-81a2-10d9a95576d2.PNG)

And This is Effect Scene. Human is showing too
![dfcxc](https://user-images.githubusercontent.com/66728383/185105993-0b2f17d3-fb5f-488d-bdf0-3bceae9a6831.PNG)

**Comment by keijiro** [comment]
> And This is Effect Scene. Human is showing too

No. The "Effect" scene is an example that adds swirling effects to people in front of the camera. I can't see any effect on your screenshot, so it isn't working correctly.

In summary, nothing work correctly on your side.

**Comment by hyunjoebrother** [comment]
> > And This is Effect Scene. Human is showing too
> 
> No. The "Effect" scene is an example that adds swirling effects to people in front of the camera. I can't see any effect on your screenshot, so it isn't working correctly.
> 
> In summary, nothing work correctly on your side.

OK I see.
Could you tell me about what is the problem about Effect Scene setting at above image..?

**Comment by keijiro** [comment]
> Could you tell me about what is the problem about Effect Scene setting at above image..?

There is no problem. It should run.

**Comment by keijiro** [comment]
I close this issue as "not relevant" (the question is not about this project but for user's private project).
