### ISSUE TITLE
Detecting only a single person

### ISSUE THREAD

**Issue by DutchRose-Jochem** [keijiro/NNCam#18]
Hi,

I have another question:
Would it be possible to just detect one person for the background removal?
So there is one person standing in front of the webcam and people that happen to walk past, for the most part, get left out.

**Comment by keijiro** [comment]
The short answer is no. BodyPix doesn't support identification. You have to implement special algorithm for it by yourself.

**Comment by DutchRose-Jochem** [comment]
Okay, thanks for your answer!
So the things described here won't work: https://github.com/tensorflow/tfjs/issues/2547 ?

**Comment by keijiro** [comment]
It would work.
(The things described there is "It can detect multiple people". Identifying them is another problem.)
