### ISSUE TITLE
How can i show whole webcam image on rawimage?

### ISSUE THREAD

**Issue by cancaglar** [keijiro/NNCam#19]
I want to show it on the raw image (ie as a UI) instead of the camera's background, but I couldn't understand where I should edit the code, can you help?

**Comment by keijiro** [comment]
Use a render texture.

**Comment by keijiro** [comment]
I'm closing this issue now as irrelevant (the original post is not a technical issue in the project but a consulting request for poster's personal project). Please reopen it for further issues.
