### ISSUE TITLE
Create a new urp project to form another scene, and even if you put urpassets, the image does not come out.

### ISSUE THREAD

**Issue by RameChoi** [keijiro/NNCam#22]
Create a new urp project to form another scene, and even if you put urpassets, the image does not come out.

**Comment by RameChoi** [comment]
how about unity 2021.3.15f?

**Comment by keijiro** [comment]
Could you describe what you're trying to do? It sounds like you're creating an empty URP project, and it's irrelevant to this project (NNCam).

**Comment by RameChoi** [comment]
> 무엇을 하려는지 설명해 주시겠습니까? 빈 URP 프로젝트를 생성하는 것처럼 들리며 이 프로젝트(NNCam)와 관련이 없습니다.

I want to create an empty urp project to get rid of the background of real space and image it with a camera in a webcam or Android/ios application.

**Comment by keijiro** [comment]
Two points:

1. This repository is dedicated to show how to use BodyPix in the built-in render pipeline. URP is out of the scope.
2. For human stencil acquisition, AR Foundation is a better solution in several points. I wouldn't recommend using this project for your purpose.

https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/manual/features/occlusion.html

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problems.
