### ISSUE TITLE
Using Video instead of 2DTexture 

### ISSUE THREAD

**Issue by justinLifelike** [keijiro/NNCam#23]
Dear Keijiro, 

Thank you for sharing this <3
I want to switch the standard image background with a video but I can't seem to find the right way. 
I am not the best programmer out there. 

But I think I have to switch 2DTexture with the RawImage which has a render texture of a video. 

![image](https://user-images.githubusercontent.com/89152236/223777517-3ca99061-e325-46dc-be3e-a5bae56a819a.png)

Could you help me out here please. 
Thanks in advance!

**Comment by keijiro** [comment]
I'd recommend using the BodyPixSample project as a starting point rather than NNCam.

https://github.com/keijiro/BodyPixSample

It uses ShaderGraph, so you can easily modify the features.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problems.
