### ISSUE TITLE
nncam

### ISSUE THREAD

**Issue by ys1317** [keijiro/NNCam#25]
Hello, firstly, the camera gives me dark lighting. I tried to add a light source, but it didn't make any changes. Secondly, I want to ask if it can be run on a mobile camera instead of a webcam for use in AR Foundation (camera - user (selfie)).
thank you .
yasmeen

**Comment by keijiro** [comment]
> the camera gives me dark lighting

Could you provide a screenshot?

> Secondly, I want to ask if it can be run on a mobile camera instead of a webcam for use in AR Foundation (camera - user (selfie)).

Yes, you can.

**Comment by keijiro** [comment]
BodyPix is not the best performant network for background segmentation. There are lighter models like this (I guess it's still slow on the device though)

https://github.com/keijiro/SelfieBarracuda

**Comment by keijiro** [comment]
I close this issue for inactivity (for the original post)
