### ISSUE TITLE
License file? 

### ISSUE THREAD

**Issue by rygo6-MS** [keijiro/NNCam#3]
Great work on this example. I notice there isn't a license file though. Is this free to use? Should this be MIT licensed?

**Comment by keijiro** [comment]
Please follow the original license. I'll add it to the repo later.

https://github.com/tensorflow/tfjs-models

**Comment by keijiro** [comment]
Soved https://github.com/keijiro/NNCam/commit/a3435edd3692d5dc3c250151cd7be241b2327c12
