### ISSUE TITLE
A better quality model

### ISSUE THREAD

**Issue by leavittx** [keijiro/NNCam#4]
I think this: https://github.com/PeterL1n/BackgroundMattingV2
have much better quality, and also have ONNX model.
The only open question for me is whether the performance will be at least on par with the python webcam demo (30fps inference for 640x360 image on mobile Nvidia GTX1050)
Could be worth trying also!

**Comment by keijiro** [comment]
I tried it some weeks ago, and it didn't work on Barracuda due to ONNX compatibility issue.

Please note that there are lots of compatibility issues with ONNX. If you find an ONNX model, it doesn't necessarily work on Barracuda.
