### ISSUE TITLE
In-game camera support

### ISSUE THREAD

**Issue by olgv** [keijiro/NNCam#5]
Thank you for this amasing pack @keijiro super useful!
This is more of a suggestion/question then a bug :)

–
Is there any implementation outside the webcam stream-in method?
For example, being able to use the distort on an in-game camera, applying it only on the 3d moving content, or using a different layer to say what is static and to be ignored.

Appreciated

**Comment by keijiro** [comment]
The main aim of this repository is human segmentation using the BodyPix neural network model. I hardly think that your suggestion works as an example for the model.
