### ISSUE TITLE
How did you edit the ResNet50 Model?

### ISSUE THREAD

**Issue by ababilinski** [keijiro/NNCam#9]
While trying to add a colored segment effect, I stumbled into the following problem: exporting the model using the [Google Colab notebook](https://colab.research.google.com/drive/1ikOMoqOX7TSBNId0lGaQ_kIyDF2GV3M3?usp=sharing) generates a model that throws the following error in Unity, `Cannot reshape array of size 943 into shape`. 

What program do you use to make the additional changes to your model? 

![ResNet50-Model-Export-Issue_NNCam](https://user-images.githubusercontent.com/7719833/120427059-3b4a1980-c33f-11eb-9daa-731eda3195ff.png)

**Comment by keijiro** [comment]
I haven't used any other program to convert the BodyPix models. My guess is that they made some changes to the BodyPix models. The Google dev team is still actively working on the tfjs models, so it's plausible.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
